# Nombre de la automatizacion de Integracion Continua (CI) Continius Integration
name: CI

# Que se ejecute siempre que haya un cambio en cualquier rama
on: push

jobs: # Defino las tareas que va a hacer este CI   

  Tarea1:  # Nombre de mi tarea
    runs-on: ubuntu-latest # Donde se va a ejecutar
    steps: # Pasos que se van a ejecutar
      # Chequea el repositorio 
      - uses: actions/checkout@v3

      - name: Saludo # Nombre de la ejecucion
        run: echo Hola, Mundo!  # Comando a ejecutar

      - name: Saludo Flaco # Nombre de la ejecucion
        run: echo Hola Flaco! # Comando a ejecutar

  Tarea2:  # Nombre de mi tarea
    runs-on: ubuntu-latest
    steps:
      - name: Saludo3 # Nombre de la ejecucion
        run: echo Hola, Gaston!  # Comando a ejecutar
