# Nombre de la automatizacion de Integracion Continua (CI) Continius Integration
name: CI

# Que se ejecute siempre que haya un cambio en cualquier rama
on: push
   

jobs: # Defino las tareas que va a hacer este CI   
 Test:  # Nombre de mi tarea
    runs-on: ubuntu-latest # Donde se va a ejecutar
    steps: # Pasos que se van a ejecutar
    
      # Chequea el repositorio 
      - uses: actions/checkout@v3
      
      - name: PHP Copy Paste Detector
        uses: StephaneBour/actions-php-cpd@1.0
        with:
          dir: '.'
          
 dependency_check:
    runs-on: ubuntu-latest
    name: Dependency check Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 1
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
