name: "Zap Proxy"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.SCANSECRET }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.admingb.com'
          cmd_options: '-x report_xml'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Zap Proxy Reporty
           path: ${{github.workspace}}
